QRCodeEvidentationApp/Models/LectureGroup.cs
using QRCodeEvidentationApp.Models;

namespace QRCodeEvidentationApp.Models
{
    public class LectureGroup
    {
        public string Id { get; set; } = null!;

        public string Name { get; set; }

        public string ProfessorId { get; set; }

        public Professor Professor { get; set; }
        public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
        
        public virtual ICollection<Lecture> Lectures { get; set; } = new List<Lecture>();
    }
}

QRCodeEvidentationApp/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QRCodeEvidentationApp.Data;
using QRCodeEvidentationApp.Models;
using QRCodeEvidentationApp.Models.DTO;
using QRCodeEvidentationApp.Models.DTO.AnalyticsDTO;
using QRCodeEvidentationApp.Service.Interface;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace QRCodeEvidentationApp.Controllers
{
    [Authorize(Roles = "PROFESSOR")]
    public class CoursesController : Controller
    {
        private readonly IProfessorService _professorService;
        private readonly ICourseService _courseService;

        public CoursesController(
            IProfessorService professorService,
            ICourseService courseService)
        {
            _professorService = professorService;
            _courseService = courseService;
        }
        
        private bool IsProfessorAssignedCourse(long? courseId)
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            Professor professor = _professorService.GetProfessorFromUserEmail(userEmail).Result;

            bool result = _courseService.ProfessorAtCourse(courseId, professor.Id);
            return result;
        }

        // GET: Courses
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            Professor professor = _professorService.GetProfessorFromUserEmail(userEmail).Result;

            List<Course> courses = _courseService.GetCourses(professor.Id);
            
            return View(courses);
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(long id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (!IsProfessorAssignedCourse(id))
            {
                return RedirectToAction(nameof(DisplayError),
                    new { error = "You are not assigned as professor to this course." });
            }

            var course = _courseService.GetCourse(id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }
        
        public IActionResult DisplayError(string error)
        {
            ErrorMessageDTO errorMessageDto = new ErrorMessageDTO();
            errorMessageDto.Message = error;
            return View(errorMessageDto);
        }
    }
}

QRCodeEvidentationApp/Controllers/LectureGroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QRCodeEvidentationApp.Data;
using QRCodeEvidentationApp.Models;
using QRCodeEvidentationApp.Models.DTO;
using QRCodeEvidentationApp.Models.DTO.AnalyticsDTO;
using QRCodeEvidentationApp.Service.Interface;

namespace QRCodeEvidentationApp.Controllers
{
    [Authorize(Roles = "PROFESSOR")]
    public class LectureGroupsController : Controller
    {
        private readonly ILectureGroupService _lectureGroupService;
        private readonly IProfessorService _professorService;
        private readonly ILectureService _lectureService;
        private readonly IGenerateExcelDocument _generateDocumentService;
        private readonly ICourseService _courseService;
        
        public LectureGroupsController( 
            ILectureGroupService lectureGroupService, 
            IProfessorService professorService,
            ILectureService lectureService,
            IGenerateExcelDocument generateDocumentService)
        {
            _lectureGroupService = lectureGroupService;
            _professorService = professorService;
            _lectureService = lectureService;
            _generateDocumentService = generateDocumentService;
        }

        private async Task<bool> IsUserCreatorOfLectureGroup(string lectureGroupId)
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var professor = await _professorService.GetProfessorFromUserEmail(userEmail ?? throw new InvalidOperationException());
    
            var lectureGroup = await _lectureGroupService.Get(lectureGroupId);
            return lectureGroup?.ProfessorId == professor.Id;
        }
        
        // GET: LectureGroups
        public async Task<IActionResult> Index()
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            Professor professor = _professorService.GetProfessorFromUserEmail(userEmail).Result;

            List<LectureGroup> lectureGroups = _lectureGroupService.ListByProfessor(professor.Id).Result;
            return View(lectureGroups);
        }

        // GET: LectureGroups/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (!await IsUserCreatorOfLectureGroup(id))
            {
                return RedirectToAction(nameof(DisplayError),
                    new { error = "The logged in professor doesn't have access to this lecture group." });
            }
            
            LectureGroup lecture = await _lectureGroupService.Get(id);

            return View(lecture);
        }

        // GET: LectureGroups/Create
        [Authorize]
        public async Task<IActionResult> Create()
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            Professor professor = _professorService.GetProfessorFromUserEmail(userEmail).Result;
            
            LectureGroupDTO data = await _lectureGroupService.PrepareForCreate(professor.Id);

            return View(data);
        }

        // POST: LectureGroups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Create([Bind("Name,SelectedCourses,ProfessorId,Courses")] LectureGroupDTO data)
        {            
            if (ModelState.IsValid)
            {
                _lectureGroupService.Create(data);

                return RedirectToAction(nameof(Index));
            }
            data = _lectureGroupService.PrepareForCreate(User.Identity.Name).Result;

            return View(data);
        }
        
        // GET: LectureGroups/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            if (!await IsUserCreatorOfLectureGroup(id))
            {
                return RedirectToAction(nameof(DisplayError),
                    new { error = "The logged in professor doesn't have access to this lecture group." });
            }

            var lectureGroup = _lectureGroupService.Get(id).Result;
            
            if (lectureGroup == null)
            {
                return NotFound();
            }

            return View(lectureGroup);
        }

        // POST: LectureGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (!await IsUserCreatorOfLectureGroup(id))
            {
                return RedirectToAction(nameof(DisplayError),
                    new { error = "The logged in professor doesn't have access to this lecture group." });
            }

            _lectureGroupService.Delete(id);
            
            return RedirectToAction(nameof(Index));
        }
        
        public IActionResult DisplayError(string error)
        {
            ErrorMessageDTO errorMessageDto = new ErrorMessageDTO();
            errorMessageDto.Message = error;
            return View(errorMessageDto);
        }
        
         public async Task<IActionResult> Analytics(string id)
        {
            if (!await IsUserCreatorOfLectureGroup(id))
            {
                return RedirectToAction(nameof(DisplayError),
                    new { error = "The logged in professor doesn't have access to this lecture group." });
            }
            
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            Professor loggedInProfessor = await _professorService.GetProfessorFromUserEmail(userEmail ?? throw new InvalidOperationException());
            
            List<Lecture> lectures = new List<Lecture>();
            lectures = _lectureService.GetLecturesByProfessorAndCourseGroupId(loggedInProfessor.Id, id);
            CourseGroupAnalyticsDTO courseAnalytics = _lectureGroupService.GetLecturesCourseGroupAnalytics(lectures, id);
            return View(courseAnalytics);
        }

        public async Task<IActionResult> GeneralAnalytics(string id)
        {
            if (!await IsUserCreatorOfLectureGroup(id))
            {
                return RedirectToAction(nameof(DisplayError),
                    new { error = "The logged in professor doesn't have access to this lecture group." });
            }
            
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            Professor loggedInProfessor = await _professorService.GetProfessorFromUserEmail(userEmail ?? throw new InvalidOperationException());
            
            var result = _generateDocumentService.GenerateDocument(loggedInProfessor, id);

            LectureGroup lectureGroup = _lectureGroupService.Get(id).Result;

            if (result is FileContentResult fileResult)
            {
                // Change the FileDownloadName
                fileResult.FileDownloadName = "aggregated_analytics_" + lectureGroup.Name + "_" + DateTime.Now + ".xlsx";
                return fileResult;
            }
            
            return result;
        }
    }
}

QRCodeEvidentationApp/Views/LectureGroups/Analytics.cshtml
@model QRCodeEvidentationApp.Models.DTO.AnalyticsDTO.CourseGroupAnalyticsDTO

@{
    ViewBag.Title = "Course Analytics";
    Layout = "_Layout";
}

<h1 class="text-center my-4">@ViewBag.Title</h1>

<div class="text-end mb-3">
    <a asp-action="GeneralAnalytics" asp-controller="LectureGroups" asp-route-id="@Model.courseGroupId" class="btn btn-primary">
        Aggregated Analytics
    </a>
</div>

<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <thead class="table-dark">
        <tr>
            <th>Title</th>
            <th>Number of attendees</th>
            <th class="text-center">Actions</th>
        </tr>
        </thead>
        <tbody>
        @if (Model.lecturesAndAttendees != null && Model.lecturesAndAttendees.Any())
        {
            foreach (var entry in Model.lecturesAndAttendees)
            {
                <tr>
                    <td>@entry.Key.Title</td>
                    <td>@entry.Value</td>
                    <td class="text-center">
                        <div class="btn-group" role="group">
                            <a asp-action="Details" asp-controller="Lectures" asp-route-id="@entry.Key.Id" class="btn btn-sm btn-primary m-1">Details</a>
                            <a asp-action="GetLectureAnalytics" asp-controller="Lectures" asp-route-id="@entry.Key.Id" class="btn btn-sm btn-primary m-1">Analytics</a>
                        </div>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="3" class="text-center">No data available.</td>
            </tr>
        }
        </tbody>
    </table>
</div>

QRCodeEvidentationApp/Views/LectureGroups/Create.cshtml
@model QRCodeEvidentationApp.Models.DTO.LectureGroupDTO

@{
ViewData["Title"] = "Create";
}

<h1 class="text-center my-4">@ViewData["Title"]</h1>

<h4 class="text-center">Create Lecture Group</h4>
<hr />

<div class="row justify-content-center">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

            <div class="form-group mb-3">
                <input type="hidden" asp-for="ProfessorId" class="form-control" />
            </div>

            <div class="form-group mb-3">
                <label asp-for="Name" class="form-label">Lecture Group Name</label>
                <input asp-for="Name" class="form-control" placeholder="Enter the lecture group name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <span>Select courses:</span>
                <select asp-for="SelectedCourses" asp-items="@(new SelectList(Model.Courses, "Id", "LastNameRegex"))" class="form-control" multiple="multiple">
                </select>
                <span asp-validation-for="SelectedCourses" class="text-danger"></span>
            </div>

            <div class="form-group text-center mb-3">
                <input type="submit" value="Create" class="btn btn-success btn-lg" />
            </div>
        </form>
    </div>
</div>

<div class="text-center mt-4">
    <a asp-action="Index" class="btn btn-link">Back to List</a>
</div>

@section Scripts {
@{
await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

QRCodeEvidentationApp/Views/LectureGroups/Delete.cshtml
@model QRCodeEvidentationApp.Models.LectureGroup

@{
ViewData["Title"] = "Delete";
}

<div class="card shadow-lg p-4 mb-4">
    <h1 class="text-center mb-4">@ViewData["Title"]</h1>

    <h3 class="text-center mb-4">Are you sure you want to delete this?</h3>

    <div>
        <h4 class="mb-3">Lecture Group</h4>
        <hr />

        <dl class="row">
            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt class="col-sm-3 font-weight-bold">
                Courses:
            </dt>
            <dd class="col-sm-9">
                <div class="mt-3">
                    @foreach (var item in Model.Courses)
                    {
                    <div class="mb-4">
                        <div class="card shadow-sm">
                            <div class="card-body d-flex justify-content-between align-items-center">
                                <h5 class="card-title mb-0">
                                    @Html.DisplayFor(modelItem => item.LastNameRegex)
                                </h5>
                                <a href="@Url.Action("Details", "Courses", new { id = item.Id })" class="btn btn-outline-primary btn-sm">View Details</a>
                            </div>
                        </div>
                    </div>
                    }
                </div>
            </dd>
        </dl>

        <form asp-action="Delete" class="mt-3">
            <input type="hidden" asp-for="Id" />
            <div class="text-center">
                <input type="submit" value="Delete" class="btn btn-danger btn-lg m-2" />
                <a asp-action="Index" class="btn btn-secondary btn-lg m-2">Back to List</a>
            </div>
        </form>
    </div>
</div>

QRCodeEvidentationApp/Views/LectureGroups/Details.cshtml
@model QRCodeEvidentationApp.Models.LectureGroup

@{
ViewData["Title"] = "Details";
Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Lecture Group Details</h1>

<div class="container mt-4">
    <div class="card">
        <div class="card-header bg-black text-white">
            <h4 class="card-title">Lecture Group Information</h4>
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-2 text-muted">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Name)
                </dd>
            </dl>
            <dl class = "row">

            <dt class="col-sm-2 text-muted">
                Courses:
            </dt>
            <dd class="col-sm-9">
                <div class="mt-3">
                    @foreach (var item in Model.Courses)
                    {
                        <div class="mb-4">
                            <div class="card shadow-sm">
                                <div class="card-body d-flex justify-content-between align-items-center">
                                    <h5 class="card-title mb-0">
                                        @Html.DisplayFor(modelItem => item.LastNameRegex)
                                    </h5>
                                    <a href="@Url.Action("Details", "Courses", new { id = item.Id })" class="btn btn-outline-primary btn-sm">View Details</a>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </dd>
        </dl>
    </div>
    </div>
</div>

<div class="mt-4 text-center">
    <a asp-action="Index" class="btn btn-secondary btn-sm">Back to List</a>
</div>

QRCodeEvidentationApp/Views/LectureGroups/DisplayError.cshtml
@model QRCodeEvidentationApp.Models.DTO.ErrorMessageDTO

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h1>@Model.Message</h1>

QRCodeEvidentationApp/Views/LectureGroups/Index.cshtml
@model IEnumerable<QRCodeEvidentationApp.Models.LectureGroup>

@{
    ViewData["Title"] = "Lecture Groups";
}

<h1 class="text-center my-4">@ViewData["Title"]</h1>

<p class="text-end">
    <a asp-action="Create" class="btn btn-success">Create New Group</a>
</p>

<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <thead class="table-dark">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th class="text-center">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr id="lecture-group-row-@item.Id">
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td class="text-center">
                    <div class="btn-group" role="group">
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-warning m-1">Details</a>
                        <a asp-action="Analytics" asp-route-id="@item.Id" class="btn btn-sm btn-primary m-1">Analytics</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger m-1 delete-group-btn">Delete</a>
                    </div>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>