QRCodeEvidentationApp/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QRCodeEvidentationApp.Data;
using QRCodeEvidentationApp.Models;
using QRCodeEvidentationApp.Models.DTO;
using QRCodeEvidentationApp.Models.DTO.AnalyticsDTO;
using QRCodeEvidentationApp.Service.Interface;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace QRCodeEvidentationApp.Controllers
{
    [Authorize(Roles = "PROFESSOR")]
    public class CoursesController : Controller
    {
        private readonly IProfessorService _professorService;
        private readonly ICourseService _courseService;

        public CoursesController(
            IProfessorService professorService,
            ICourseService courseService)
        {
            _professorService = professorService;
            _courseService = courseService;
        }
        
        private bool IsProfessorAssignedCourse(long? courseId)
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            Professor professor = _professorService.GetProfessorFromUserEmail(userEmail).Result;

            bool result = _courseService.ProfessorAtCourse(courseId, professor.Id);
            return result;
        }

        // GET: Courses
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            Professor professor = _professorService.GetProfessorFromUserEmail(userEmail).Result;

            List<Course> courses = _courseService.GetCourses(professor.Id);
            
            return View(courses);
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(long id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (!IsProfessorAssignedCourse(id))
            {
                return RedirectToAction(nameof(DisplayError),
                    new { error = "You are not assigned as professor to this course." });
            }

            var course = _courseService.GetCourse(id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }
        
        public IActionResult DisplayError(string error)
        {
            ErrorMessageDTO errorMessageDto = new ErrorMessageDTO();
            errorMessageDto.Message = error;
            return View(errorMessageDto);
        }
    }
}

QRCodeEvidentationApp/Controllers/LecturesController.cs
using System.Security.Claims;
using ClosedXML.Excel;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QRCodeEvidentationApp.Models;
using QRCodeEvidentationApp.Models.DTO;
using QRCodeEvidentationApp.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using QRCodeEvidentationApp.Service.Implementation;
using QRCoder;


namespace QRCodeEvidentationApp.Controllers
{
    [Authorize(Roles = "PROFESSOR")]
    public class LecturesController : Controller
    {
        private readonly ILectureService _lectureService;
        private readonly IProfessorService _professorService;
        private readonly ICourseService _courseService;
        private readonly ILectureGroupService _lectureGroupService;
        private readonly ILectureAttendanceService _lectureAttendanceService;
        private readonly IGenerateExcelDocument _generateExcelService;
        private readonly IQrCodeService _qrCodeService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public LecturesController(ILectureService lectureService, 
            IProfessorService professorService,
            ICourseService courseService,
            ILectureGroupService lectureGroupService,
            ILectureAttendanceService lectureAttendanceService,
            IGenerateExcelDocument generateExcelService,
            IQrCodeService qrCodeService,
            IWebHostEnvironment webHostEnvironment
            )
        {
            _lectureService = lectureService;
            _professorService = professorService;
            _courseService = courseService;
            _lectureGroupService = lectureGroupService;
            _lectureAttendanceService = lectureAttendanceService;
            _generateExcelService = generateExcelService;
            _qrCodeService = qrCodeService;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Lecture
        public async Task<IActionResult> Index(int page = 1, int pageSize = 10, int startsAtSorting = 0, string lecturesTypeFilter = "")
        {
            // take the logged in user
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
    
            // Get the logged in user's roles
            var userRoles = User.Claims
                .Where(c => c.Type == ClaimTypes.Role)
                .Select(c => c.Value)
                .ToList();

            List<Lecture> lectures = null;
            bool isProfessor = User.IsInRole("PROFESSOR");
            int totalLectures = 0; // Variable to store the total number of lectures

            if (isProfessor)
            {
                Professor loggedInProfessor = await _professorService.GetProfessorFromUserEmail(userEmail ?? throw new InvalidOperationException());
        
                // Get the paginated lectures and total lecture count
                lectures = _lectureService.GetLecturesForProfessorFiltered(loggedInProfessor.Id, page, pageSize, startsAtSorting, lecturesTypeFilter, out totalLectures);
            }

            // Calculate total pages based on total lectures and page size
            var totalPages = (int)Math.Ceiling(totalLectures / (double)pageSize);

            // Pass data to the view including pagination metadata
            var model = new PaginatedLecturesViewModel
            {
                Lectures = lectures,
                CurrentPage = page,
                TotalPages = totalPages,
                PageSize = pageSize,
                TotalLectures = totalLectures
            };

            return View(model);
        }

        public IActionResult BulkAddLecturesView()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult BulkAddLecturesView(IFormFile csvFile)
        {
            if (csvFile != null && csvFile.Length > 0)
            {
                // PARSE THE CSV RECORDS AND ADD THE RECORDS IN THE DATABASE
                var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
                
                
                _lectureService.BulkInsertLectures(csvFile, userEmail);
                return RedirectToAction("Index");
            }
            
            // If no file is uploaded, return to the same view with an error message
            ModelState.AddModelError("csvFile", "Please upload a CSV file.");
            return View();
        }

        // GET: Lecture/Details/5
        public IActionResult Details(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lecture = _lectureService.GetLectureById(id);

            return View(lecture);
        }

        // GET: Lecture/Create
        [HttpGet]
        public async Task<IActionResult> CreateView()
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            LectureDto dto = new LectureDto();
            Professor loggedInProfessor = await _professorService.GetProfessorFromUserEmail(userEmail ?? throw new InvalidOperationException());

            dto.CoursesProfessor = await _courseService.GetCoursesForProfessor(loggedInProfessor.Id);
            dto.CoursesAssistant = await _courseService.GetCoursesForAssistant(loggedInProfessor.Id);
            dto.Groups = await _lectureGroupService.ListByProfessor(loggedInProfessor.Id);
            dto.loggedInProfessorId = loggedInProfessor.Id;

            dto.StartsAt = DateTime.Now.Date;
            dto.EndsAt = DateTime.Now.Date;
            dto.ValidRegistrationUntil = DateTime.Now.Date;

            return View("Create", dto);
        }

        // POST: Lecture/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(LectureDto dtoFilled)
        {
            if (ModelState.IsValid)
            {
                _lectureService.CreateLecture(dtoFilled);
                return RedirectToAction(nameof(Index));
            }
            
            return View(dtoFilled);
        }

        // GET: Lecture/Edit/5
        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lecture = _lectureService.GetLectureById(id);
            LectureEditDto dto = new LectureEditDto();
            
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            
            Professor loggedInProfessor = await _professorService.GetProfessorFromUserEmail(userEmail ?? throw new InvalidOperationException());

            Lecture lectureProfessor = _lectureService.GetLectureForProfessor(loggedInProfessor.Id);
            if (lectureProfessor == null)
            {
                return RedirectToAction(nameof(DisplayError), new { error = "The logged in professor doesn't have access to this lecture."});
            }

            dto.Groups = await _lectureGroupService.ListByProfessor(loggedInProfessor.Id);

            dto.lecture = lecture;
            dto.lectureId = id;
            
            return View(dto);
        }

        // POST: Lecture/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, LectureEditDto lectureDto)
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            
            Professor loggedInProfessor = await _professorService.GetProfessorFromUserEmail(userEmail ?? throw new InvalidOperationException());

            Lecture lectureProfessor = _lectureService.GetLectureForProfessor(loggedInProfessor.Id);
            if (lectureProfessor == null)
            {
                return RedirectToAction(nameof(DisplayError),
                    new { error = "The logged in professor doesn't have access to this lecture." });
            }

            if (id != lectureDto.lectureId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var existingLecture = _lectureService.GetLectureById(id);
                
                if (existingLecture == null)
                {
                    return NotFound();
                }

                // Update the properties of the existing lecture with the properties from the DTO
                existingLecture.Title = lectureDto.lecture.Title;
                existingLecture.StartsAt = lectureDto.lecture.StartsAt;
                existingLecture.EndsAt = lectureDto.lecture.EndsAt;
                existingLecture.ValidRegistrationUntil = lectureDto.lecture.ValidRegistrationUntil;
                existingLecture.Type = lectureDto.lecture.Type;
                existingLecture.LectureGroupId = lectureDto.GroupCourseId;

                _lectureService.EditLecture(existingLecture);

                return RedirectToAction(nameof(Index));
            }
            return View(lectureDto);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DisableLecture(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return Json(new { success = false, message = "Invalid lecture ID." });
            }

            try
            {
                var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            

QRCodeEvidentationApp/Controllers/StudentController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QRCodeEvidentationApp.Models;
using QRCodeEvidentationApp.Models.DTO;
using QRCodeEvidentationApp.Service.Interface;

namespace QRCodeEvidentationApp.Controllers;

public class StudentController : Controller
{
    private readonly IStudentService _studentService;
    private readonly ILectureService _lectureService;
    private readonly ILectureAttendanceService _lectureAttendanceService;

    public StudentController(IStudentService studentService,
        ILectureService lectureService,
        ILectureAttendanceService lectureAttendanceService)
    { 
        _studentService = studentService;
        _lectureService = lectureService;
        _lectureAttendanceService = lectureAttendanceService;
    }

    [HttpGet]
    [Authorize]
    public IActionResult RegisterAttendance(string id)
    {
        ErrorMessageDTO message = new ErrorMessageDTO();
        var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
        Student student = _studentService.GetStudentFromUserEmail(userEmail).Result;
        
        LectureAttendance? attendance = _lectureAttendanceService.FindStudentRegistration(student.StudentIndex, id);

        if (attendance != null)
        {
            message.Message += "\nYou are already registered for this lecture.";
            return View(message);
        }
        
        _lectureService.RegisterAttendance(student, id, DateTime.Now);
        return RedirectToAction("Index", "Home");
    }
}

QRCodeEvidentationApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using QRCodeEvidentationApp.Models
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QRCodeEvidentationApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.5/css/jquery.dataTables.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QRCodeEvidentationApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QRCodeEvidentationApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            var user = await UserManager.GetUserAsync(User);
                            if (user != null)
                            {
                                var roles = await UserManager.GetRolesAsync(user);
                                if (roles.Contains("PROFESSOR"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Lectures" asp-action="Index">Lectures</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="LectureGroups" asp-action="Index">Course Groups</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                                    </li>
                                }
                                else if (roles.Contains("STUDENT"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student Page</a>
                                    </li>
                                }
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - QRCodeEvidentationApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
    <!-- Include scripts at the end of the body -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"></script>
    <script src="https://cdn.datatables.net/plug-ins/1.13.5/sorting/datetime-moment.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>